# Stage 1: Build-Prozess
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Production-Image
FROM alpine:latest
WORKDIR /srv
# Kopiert den SvelteKit-Build direkt in das Volume unter /srv/build
COPY --from=builder /app/build /srv/build
